{
	"patcher" : {
		"fileversion" : 1,
		"appversion" : { "major" : 8, "minor" : 5, "revision" : 0, "architecture" : "x64", "modernui" : 1 },
		"classnamespace" : "box",
		"rect" : [ 60.0, 80.0, 640.0, 480.0 ],
		"boxes" : [
			{ "box" : { "id" : "obj-1", "maxclass" : "newobj", "text" : "plugin~", "numinlets" : 0, "numoutlets" : 2, "outlettype" : [ "signal", "signal" ], "patching_rect" : [ 40.0, 40.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-2", "maxclass" : "newobj", "text" : "plugout~", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [ 40.0, 120.0, 70.0, 22.0 ] } },

			{ "box" : { "id" : "obj-3", "maxclass" : "newobj", "text" : "udpreceive 9000", "numinlets" : 0, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 220.0, 40.0, 110.0, 22.0 ] } },
			{ "box" : { "id" : "obj-4", "maxclass" : "newobj", "text" : "route /kendama/ken/accel /kendama/tama/accel", "numinlets" : 1, "numoutlets" : 3, "outlettype" : [ "", "", "" ], "patching_rect" : [ 220.0, 80.0, 300.0, 22.0 ] } },
			{ "box" : { "id" : "obj-5", "maxclass" : "newobj", "text" : "unpack 0 0. 0. 0.", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "int", "float", "float", "float" ], "patching_rect" : [ 220.0, 120.0, 120.0, 22.0 ] } },
			{ "box" : { "id" : "obj-6", "maxclass" : "newobj", "text" : "* 0.05", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 240.0, 170.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-7", "maxclass" : "newobj", "text" : "+ 0.5", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 240.0, 210.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-8", "maxclass" : "newobj", "text" : "clip 0. 1.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 240.0, 250.0, 65.0, 22.0 ] } },
			{ "box" : { "id" : "obj-9", "maxclass" : "newobj", "text" : "line~", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [ 240.0, 300.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-34", "maxclass" : "newobj", "text" : "pack 0. 20", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 330.0, 275.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-10", "maxclass" : "newobj", "text" : "live.remote~ @normalized 1", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [ 240.0, 350.0, 170.0, 22.0 ] } },
			{ "box" : { "id" : "obj-11", "maxclass" : "message", "text" : "1", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 470.0, 300.0, 30.0, 22.0 ] } },
			{ "box" : { "id" : "obj-12", "maxclass" : "newobj", "text" : "live.map", "numinlets" : 1, "numoutlets" : 5, "outlettype" : [ "", "", "", "", "" ], "patching_rect" : [ 470.0, 350.0, 70.0, 22.0 ] } },

			{ "box" : { "id" : "obj-13", "maxclass" : "newobj", "text" : "* 15.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 170.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-14", "maxclass" : "newobj", "text" : "+ 128.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 210.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-15", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 560.0, 250.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-16", "maxclass" : "newobj", "text" : "* 15.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 660.0, 170.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-17", "maxclass" : "newobj", "text" : "+ 128.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 660.0, 210.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-18", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 660.0, 250.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-19", "maxclass" : "newobj", "text" : "* 12.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 760.0, 170.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-20", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 760.0, 250.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-21", "maxclass" : "newobj", "text" : "pack 0 0 0", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 300.0, 90.0, 22.0 ] } },
			{ "box" : { "id" : "obj-22", "maxclass" : "newobj", "text" : "prepend /kendama/ken/led/rgb", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 340.0, 200.0, 22.0 ] } },
			{ "box" : { "id" : "obj-23", "maxclass" : "newobj", "text" : "udpsend 127.0.0.1 9001", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 560.0, 380.0, 160.0, 22.0 ] } },

			{ "box" : { "id" : "obj-24", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 480.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-25", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 300.0, 480.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-26", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 400.0, 480.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-27", "maxclass" : "newobj", "text" : "+", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 520.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-28", "maxclass" : "newobj", "text" : "+", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 560.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-29", "maxclass" : "newobj", "text" : "sqrt", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 600.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-30", "maxclass" : "newobj", "text" : "> 18.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 640.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-31", "maxclass" : "newobj", "text" : "change", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 680.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-32", "maxclass" : "newobj", "text" : "sel 1", "numinlets" : 2, "numoutlets" : 2, "outlettype" : [ "bang", "" ], "patching_rect" : [ 200.0, 720.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-33", "maxclass" : "message", "text" : "255 255 255", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 760.0, 90.0, 22.0 ] } },

			{ "box" : { "id" : "obj-50", "maxclass" : "newobj", "text" : "unpack 0 0. 0. 0.", "numinlets" : 1, "numoutlets" : 4, "outlettype" : [ "int", "float", "float", "float" ], "patching_rect" : [ 220.0, 920.0, 120.0, 22.0 ] } },
			{ "box" : { "id" : "obj-51", "maxclass" : "newobj", "text" : "* 0.05", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 240.0, 970.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-52", "maxclass" : "newobj", "text" : "+ 0.5", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 240.0, 1010.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-53", "maxclass" : "newobj", "text" : "clip 0. 1.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 240.0, 1050.0, 65.0, 22.0 ] } },
			{ "box" : { "id" : "obj-54", "maxclass" : "newobj", "text" : "pack 0. 20", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 330.0, 1075.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-55", "maxclass" : "newobj", "text" : "line~", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "signal" ], "patching_rect" : [ 240.0, 1100.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-56", "maxclass" : "newobj", "text" : "live.remote~ @normalized 1", "numinlets" : 2, "numoutlets" : 0, "patching_rect" : [ 240.0, 1150.0, 170.0, 22.0 ] } },
			{ "box" : { "id" : "obj-57", "maxclass" : "message", "text" : "1", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 470.0, 1100.0, 30.0, 22.0 ] } },
			{ "box" : { "id" : "obj-58", "maxclass" : "newobj", "text" : "live.map", "numinlets" : 1, "numoutlets" : 5, "outlettype" : [ "", "", "", "", "" ], "patching_rect" : [ 470.0, 1150.0, 70.0, 22.0 ] } },
			{ "box" : { "id" : "obj-59", "maxclass" : "newobj", "text" : "* 15.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 970.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-60", "maxclass" : "newobj", "text" : "+ 128.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 1010.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-61", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 560.0, 1050.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-62", "maxclass" : "newobj", "text" : "* 15.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 660.0, 970.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-63", "maxclass" : "newobj", "text" : "+ 128.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 660.0, 1010.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-64", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 660.0, 1050.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-65", "maxclass" : "newobj", "text" : "* 12.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 760.0, 970.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-66", "maxclass" : "newobj", "text" : "clip 0. 255.", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "float" ], "patching_rect" : [ 760.0, 1050.0, 75.0, 22.0 ] } },
			{ "box" : { "id" : "obj-67", "maxclass" : "newobj", "text" : "pack 0 0 0", "numinlets" : 3, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 1100.0, 90.0, 22.0 ] } },
			{ "box" : { "id" : "obj-68", "maxclass" : "newobj", "text" : "prepend /kendama/tama/led/rgb", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 560.0, 1140.0, 200.0, 22.0 ] } },
			{ "box" : { "id" : "obj-69", "maxclass" : "newobj", "text" : "udpsend 127.0.0.1 9001", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 560.0, 1180.0, 160.0, 22.0 ] } },
			{ "box" : { "id" : "obj-70", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1280.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-71", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 300.0, 1280.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-72", "maxclass" : "newobj", "text" : "pow 2.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 400.0, 1280.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-73", "maxclass" : "newobj", "text" : "+", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1320.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-74", "maxclass" : "newobj", "text" : "+", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1360.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-75", "maxclass" : "newobj", "text" : "sqrt", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1400.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-76", "maxclass" : "newobj", "text" : "> 18.", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1440.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-77", "maxclass" : "newobj", "text" : "change", "numinlets" : 1, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1480.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-78", "maxclass" : "newobj", "text" : "sel 1", "numinlets" : 2, "numoutlets" : 2, "outlettype" : [ "bang", "" ], "patching_rect" : [ 200.0, 1520.0, 45.0, 22.0 ] } },
			{ "box" : { "id" : "obj-79", "maxclass" : "message", "text" : "255 255 255", "numinlets" : 2, "numoutlets" : 1, "outlettype" : [ "" ], "patching_rect" : [ 200.0, 1560.0, 90.0, 22.0 ] } },

			{ "box" : { "id" : "obj-c", "maxclass" : "comment", "text" : "Two instruments. KEN branch (top) + TAMA branch (lower), each: route accel -> live.remote~ (Map a Live param) + accel->RGB LED out :9001 + tap->white flash. plugin~->plugout~ passes audio so the track isn't muted. MAP BOTH live.remote~ objects: lock the patcher, click the '1' message above each live.map, then click the Live param it should drive.", "numinlets" : 1, "numoutlets" : 0, "patching_rect" : [ 360.0, 600.0, 320.0, 110.0 ] } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-1", 0 ], "destination" : [ "obj-2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-1", 1 ], "destination" : [ "obj-2", 1 ] } },
			{ "patchline" : { "source" : [ "obj-3", 0 ], "destination" : [ "obj-4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-4", 0 ], "destination" : [ "obj-5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 1 ], "destination" : [ "obj-6", 0 ] } },
			{ "patchline" : { "source" : [ "obj-6", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-8", 0 ] } },
			{ "patchline" : { "source" : [ "obj-8", 0 ], "destination" : [ "obj-34", 0 ] } },
			{ "patchline" : { "source" : [ "obj-34", 0 ], "destination" : [ "obj-9", 0 ] } },
			{ "patchline" : { "source" : [ "obj-9", 0 ], "destination" : [ "obj-10", 0 ] } },
			{ "patchline" : { "source" : [ "obj-11", 0 ], "destination" : [ "obj-12", 0 ] } },
			{ "patchline" : { "source" : [ "obj-12", 1 ], "destination" : [ "obj-10", 1 ] } },
			{ "patchline" : { "source" : [ "obj-5", 1 ], "destination" : [ "obj-13", 0 ] } },
			{ "patchline" : { "source" : [ "obj-13", 0 ], "destination" : [ "obj-14", 0 ] } },
			{ "patchline" : { "source" : [ "obj-14", 0 ], "destination" : [ "obj-15", 0 ] } },
			{ "patchline" : { "source" : [ "obj-15", 0 ], "destination" : [ "obj-21", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 2 ], "destination" : [ "obj-16", 0 ] } },
			{ "patchline" : { "source" : [ "obj-16", 0 ], "destination" : [ "obj-17", 0 ] } },
			{ "patchline" : { "source" : [ "obj-17", 0 ], "destination" : [ "obj-18", 0 ] } },
			{ "patchline" : { "source" : [ "obj-18", 0 ], "destination" : [ "obj-21", 1 ] } },
			{ "patchline" : { "source" : [ "obj-5", 3 ], "destination" : [ "obj-19", 0 ] } },
			{ "patchline" : { "source" : [ "obj-19", 0 ], "destination" : [ "obj-20", 0 ] } },
			{ "patchline" : { "source" : [ "obj-20", 0 ], "destination" : [ "obj-21", 2 ] } },
			{ "patchline" : { "source" : [ "obj-21", 0 ], "destination" : [ "obj-22", 0 ] } },
			{ "patchline" : { "source" : [ "obj-22", 0 ], "destination" : [ "obj-23", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 1 ], "destination" : [ "obj-24", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 2 ], "destination" : [ "obj-25", 0 ] } },
			{ "patchline" : { "source" : [ "obj-5", 3 ], "destination" : [ "obj-26", 0 ] } },
			{ "patchline" : { "source" : [ "obj-24", 0 ], "destination" : [ "obj-27", 0 ] } },
			{ "patchline" : { "source" : [ "obj-25", 0 ], "destination" : [ "obj-27", 1 ] } },
			{ "patchline" : { "source" : [ "obj-27", 0 ], "destination" : [ "obj-28", 0 ] } },
			{ "patchline" : { "source" : [ "obj-26", 0 ], "destination" : [ "obj-28", 1 ] } },
			{ "patchline" : { "source" : [ "obj-28", 0 ], "destination" : [ "obj-29", 0 ] } },
			{ "patchline" : { "source" : [ "obj-29", 0 ], "destination" : [ "obj-30", 0 ] } },
			{ "patchline" : { "source" : [ "obj-30", 0 ], "destination" : [ "obj-31", 0 ] } },
			{ "patchline" : { "source" : [ "obj-31", 0 ], "destination" : [ "obj-32", 0 ] } },
			{ "patchline" : { "source" : [ "obj-32", 0 ], "destination" : [ "obj-33", 0 ] } },
			{ "patchline" : { "source" : [ "obj-33", 0 ], "destination" : [ "obj-22", 0 ] } },

			{ "patchline" : { "source" : [ "obj-4", 1 ], "destination" : [ "obj-50", 0 ] } },
			{ "patchline" : { "source" : [ "obj-50", 1 ], "destination" : [ "obj-51", 0 ] } },
			{ "patchline" : { "source" : [ "obj-51", 0 ], "destination" : [ "obj-52", 0 ] } },
			{ "patchline" : { "source" : [ "obj-52", 0 ], "destination" : [ "obj-53", 0 ] } },
			{ "patchline" : { "source" : [ "obj-53", 0 ], "destination" : [ "obj-54", 0 ] } },
			{ "patchline" : { "source" : [ "obj-54", 0 ], "destination" : [ "obj-55", 0 ] } },
			{ "patchline" : { "source" : [ "obj-55", 0 ], "destination" : [ "obj-56", 0 ] } },
			{ "patchline" : { "source" : [ "obj-57", 0 ], "destination" : [ "obj-58", 0 ] } },
			{ "patchline" : { "source" : [ "obj-58", 1 ], "destination" : [ "obj-56", 1 ] } },
			{ "patchline" : { "source" : [ "obj-50", 1 ], "destination" : [ "obj-59", 0 ] } },
			{ "patchline" : { "source" : [ "obj-59", 0 ], "destination" : [ "obj-60", 0 ] } },
			{ "patchline" : { "source" : [ "obj-60", 0 ], "destination" : [ "obj-61", 0 ] } },
			{ "patchline" : { "source" : [ "obj-61", 0 ], "destination" : [ "obj-67", 0 ] } },
			{ "patchline" : { "source" : [ "obj-50", 2 ], "destination" : [ "obj-62", 0 ] } },
			{ "patchline" : { "source" : [ "obj-62", 0 ], "destination" : [ "obj-63", 0 ] } },
			{ "patchline" : { "source" : [ "obj-63", 0 ], "destination" : [ "obj-64", 0 ] } },
			{ "patchline" : { "source" : [ "obj-64", 0 ], "destination" : [ "obj-67", 1 ] } },
			{ "patchline" : { "source" : [ "obj-50", 3 ], "destination" : [ "obj-65", 0 ] } },
			{ "patchline" : { "source" : [ "obj-65", 0 ], "destination" : [ "obj-66", 0 ] } },
			{ "patchline" : { "source" : [ "obj-66", 0 ], "destination" : [ "obj-67", 2 ] } },
			{ "patchline" : { "source" : [ "obj-67", 0 ], "destination" : [ "obj-68", 0 ] } },
			{ "patchline" : { "source" : [ "obj-68", 0 ], "destination" : [ "obj-69", 0 ] } },
			{ "patchline" : { "source" : [ "obj-50", 1 ], "destination" : [ "obj-70", 0 ] } },
			{ "patchline" : { "source" : [ "obj-50", 2 ], "destination" : [ "obj-71", 0 ] } },
			{ "patchline" : { "source" : [ "obj-50", 3 ], "destination" : [ "obj-72", 0 ] } },
			{ "patchline" : { "source" : [ "obj-70", 0 ], "destination" : [ "obj-73", 0 ] } },
			{ "patchline" : { "source" : [ "obj-71", 0 ], "destination" : [ "obj-73", 1 ] } },
			{ "patchline" : { "source" : [ "obj-73", 0 ], "destination" : [ "obj-74", 0 ] } },
			{ "patchline" : { "source" : [ "obj-72", 0 ], "destination" : [ "obj-74", 1 ] } },
			{ "patchline" : { "source" : [ "obj-74", 0 ], "destination" : [ "obj-75", 0 ] } },
			{ "patchline" : { "source" : [ "obj-75", 0 ], "destination" : [ "obj-76", 0 ] } },
			{ "patchline" : { "source" : [ "obj-76", 0 ], "destination" : [ "obj-77", 0 ] } },
			{ "patchline" : { "source" : [ "obj-77", 0 ], "destination" : [ "obj-78", 0 ] } },
			{ "patchline" : { "source" : [ "obj-78", 0 ], "destination" : [ "obj-79", 0 ] } },
			{ "patchline" : { "source" : [ "obj-79", 0 ], "destination" : [ "obj-68", 0 ] } }
		]
	}
}
