[env:instrument]
platform = espressif32
board = adafruit_feather_esp32s3_nopsram
framework = arduino
monitor_speed = 921600
lib_deps =
    ; Add libraries as needed during development
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
